"""Update AnswerRecord model fields

Revision ID: a64f8e3fab2a
Revises: 3697ff337f3e
Create Date: 2025-04-14 21:56:56.201781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64f8e3fab2a'
down_revision = '3697ff337f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_answer', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('answered_at')
        batch_op.drop_column('user_answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_answer', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('answered_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('selected_answer')

    # ### end Alembic commands ###
